@startuml Class Diagram - Main Indexing Flow - Orchestration

top to bottom direction
skinparam classAttributeIconSize 0
skinparam classFontStyle bold
skinparam packageStyle rectangle
skinparam linetype ortho
hide empty members

title Orchestration - ApplicationBootstrap, IndexDipUC


  class ApplicationBootstrap {
    - indexDipUC: IndexDipUC
    + bootstrap(dipPath: string): Promise<void>
  }

  interface IIndexDipUC {
    + execute(dipPath: string): Promise<void>
  }

  class IndexDipUC implements IIndexDipUC {
     - packageReader: IPackageReaderPort
     - dipRepository: IDipRepository
     - documentClassRepository: IDocumentClassRepository
     - processRepository: IProcessRepository
     - documentRepository: IDocumentRepository
     - fileRepository: IFileRepository
     - vectorRepository: IVectorRepository
     - embeddingService: IEmbeddingService
     + execute(dipPath: string): Promise<IndexResult>
     - indexDip(): Promise<IndexResult>
     - indexDocumentClasses(): Promise<IndexResult>
     - indexProcesses(): Promise<IndexResult>
     - indexDocuments(): Promise<IndexResult>
     - indexFiles(): Promise<IndexResult>
     - indexMainFileVector(file: File): Promise<void>
  }

  class IndexResult{
     - success: boolean
  }


interface IEmbeddingService {}
interface IPackageReaderPort {}

ApplicationBootstrap --> IIndexDipUC
IndexDipUC --> IPackageReaderPort
IndexDipUC --> IEmbeddingService
IndexDipUC --> IndexResult
@enduml
