@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component_Boundary(main,"Main", "Node.js, TypeScript", "Processo principale che gestisce la logica di business pesante, l'indicizzazione e l'accesso diretto alle risorse locali."){
    Component(dip_uploader, "DIP Uploader", "Node.js, TypeScript", "Componente che gestisce l'importazione dei pacchetti DIP, estraendo i file XML e preparando i dati per l'indicizzazione.")
    Component(file_parser, "File Parser", "Node.js, TypeScript", "Componente responsabile dell'analisi e dell'estrazione dei dati dai file XML all'interno del pacchetto DIP.")
    Component(indexer, "Indexer", "Node.js, TypeScript", "Componente che indicizza i metadati estratti e li memorizza nel database SQLite.")
    Component(semantic_indexer, "Semantic Indexer", "Node.js, TypeScript", "Componente che genera vettori semantici dai metadati indicizzati e li memorizza nel database SQLite.")
    Component(search_engine, "Search Engine", "Node.js, TypeScript", "Componente che gestisce le query di ricerca, sia testuali che semantiche, utilizzando il database SQLite e i modelli LLM.")
    Component(sema_search_engine, "Semantic Search Engine", "Node.js, TypeScript", "Componente che gestisce le query di ricerca semantica, utilizzando i vettori memorizzati e i modelli LLM per restituire risultati pertinenti.")
    Component(verification_engine, "Verification Engine", "Node.js, TypeScript", "Componente che verifica l'integrità e l'autenticità dei file all'interno del DIP, calcolando hash e verificando firme digitali.")
    Component(export_manager, "Export Manager", "Node.js, TypeScript", "Componente che gestisce l'estrazione fisica dei file dal DIP per la stampa o il download.")
    Component(ipc_handler, "IPC Handler", "Node.js, TypeScript", "Componente che gestisce tutte le comunicazioni IPC con il frontend Angular, fungendo da intermediario tra le richieste dell'interfaccia utente e i servizi di backend.")
    Component(dbManager, "Database Manager", "Node.js, TypeScript", "Componente che gestisce tutte le operazioni di lettura/scrittura sui database SQLite, sia per i metadati che per i vettori semantici.")
    Component(sema_dbManager, "Semantic Database Manager", "Node.js, TypeScript", "Componente specializzato nella gestione dei vettori semantici all'interno del database SQLite, ottimizzato per le operazioni di ricerca semantica.")
   
    Component(llm_inference, "LLM Inference Engine", "transformers.js, TypeScript", "Componente che gestisce l'inferenza utilizzando i modelli LLM locali per migliorare la pertinenza dei risultati di ricerca e fornire funzionalità avanzate come il completamento automatico e la generazione di suggerimenti.")
}

Rel()
@endluml